### ISSUE TITLE
Remove setq lexical-binding from tco.el?

### ISSUE THREAD

**Issue by stephan-cr** [Wilfred/tco.el#7]
I guess `(setq lexical-binding t)` should be removed. Lexical binding is already declared at the top of the module, which is sufficient. Furthermore, according to [SO](https://stackoverflow.com/questions/35585121/lexical-binding-not-being-enabled-when-evaluating-emacs) it's dangerous.

**Comment by Wilfred** [comment]
I agree. Thanks :)
